on: push
name: Build and test
jobs:
  unit_tests:
    name: Unit tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
        matrix:
            composer-update: ["", "--prefer-stable --prefer-lowest"]
    steps:
    - uses: actions/checkout@master
    - name: Composer install
      uses: MilesChou/composer-action@master
      with:
        args: install
    - name: Composer update
      uses: MilesChou/composer-action@master
      if: "matrix.composer-update != ''"
      with:
        args: update ${{ matrix.composer-update }}
    - name: Unit tests
      uses: docker://php:7.3-alpine
      with:
        entrypoint: phpdbg
        args: -qrr vendor/bin/phpunit
    - name: Unit Codecov
      uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
