on: push
name: Build and test
jobs:
  unit_tests:
    name: Unit tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
        matrix:
            composer-update: ["", "--prefer-stable --prefer-lowest"]
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        tools: composer:v2
        # We're using phpdbg, we don't need a coverage extension.
        coverage: none
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    # Tell composer to update to the lowest supported version, if it's
    # that part of the matrix we're running.
    - name: Composer update
      if: "matrix.composer-update != ''"
      run: |
          composer update ${{ matrix.composer-update }}
    - name: Unit tests
      run: |
        phpdbg -qrr vendor/bin/phpunit
    - name: Report coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash)
